
import json
import os
import glob
from collections import Counter
from index_manager import load_manifest, load_index

OUT_FILE = "PROJECT_SNAPSHOT.md"
DATASET_DIR = "dataset"

def get_dataset_folder_summary():
    lines = []
    if not os.path.isdir(DATASET_DIR):
        return "  (no dataset/ folder found)"
    for folder in sorted(os.listdir(DATASET_DIR)):
        full = os.path.join(DATASET_DIR, folder)
        if not os.path.isdir(full):
            continue
        files = glob.glob(f"{full}/*.json")
        lines.append(f"  - dataset/{folder}/ — {len(files)} files")
    return "\n".join(lines) if lines else "  (empty)"

def get_sample_record(folder):
    files = sorted(glob.glob(f"{DATASET_DIR}/{folder}/*.json"))
    if not files:
        return None
    with open(files[0], encoding="utf-8") as f:
        data = json.load(f)

    if isinstance(data, list):
        return {"file": os.path.basename(files[0]), "keys": f"(list, length {len(data)})"}

    result = data.get("result", data)
    if isinstance(result, dict):
        keys = list(result.keys())
    else:
        keys = "(not a dict)"
    return {
        "file": os.path.basename(files[0]),
        "keys": keys
    }

def get_repo_root_files():
    exts = ("*.py", "*.json", "*.jsonl", "*.md")
    files = []
    for ext in exts:
        files.extend(glob.glob(ext))
    return sorted(set(files))

def main():
    manifest = load_manifest()
    embeddings, chunks = load_index()

    type_counts = Counter(
        c.get("metadata", {}).get("type", c.get("topic", "unknown"))
        for c in chunks
    )

    lines = []
    lines.append("# Genshin Impact RAG Wiki Assistant — Project Snapshot")
    lines.append("(Auto-generated by generate_project_snapshot.py — paste this whole file")
    lines.append("into a new conversation to restore full project context.)\n")

    lines.append("## Index / Manifest State")
    lines.append(f"- Total chunks in index: {manifest.get('total_chunks', len(chunks))}")
    lines.append(f"- Total embeddings: {len(embeddings)}")
    lines.append(f"- Last updated: {manifest.get('last_updated')}")
    lines.append("- Indexed sources:")
    for src_id, info in manifest.get("indexed_sources", {}).items():
        action = "updated" if "updated" in info else "added"
        date = info.get("updated", info.get("added", "unknown"))
        lines.append(f"  - {src_id}: {info.get('chunk_count')} chunks ({action}: {date})")
    lines.append("")

    lines.append("## Chunk Type Breakdown (from live index)")
    for ctype, count in type_counts.most_common():
        lines.append(f"  - {ctype}: {count}")
    lines.append("")

    lines.append("## Dataset Folder Structure")
    lines.append(get_dataset_folder_summary())
    lines.append("")

    lines.append("## Sample Record Keys Per Dataset Folder")
    lines.append("(shows what fields exist in raw source JSON — useful for spotting unused fields)")
    if os.path.isdir(DATASET_DIR):
        for folder in sorted(os.listdir(DATASET_DIR)):
            if not os.path.isdir(os.path.join(DATASET_DIR, folder)):
                continue
            sample = get_sample_record(folder)
            if sample:
                lines.append(f"\n### dataset/{folder}/")
                lines.append(f"- Sample file: {sample['file']}")
                lines.append(f"- Top-level keys: {sample['keys']}")
    lines.append("")

    lines.append("## Project Root Files")
    for f in get_repo_root_files():
        lines.append(f"  - {f}")
    lines.append("")

    lines.append("## Notes")
    lines.append("- Add any manual notes about current priorities / next steps below this line,")
    lines.append("  since this script only captures what's on disk, not your plans.")
    lines.append("")

    with open(OUT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"Wrote {OUT_FILE} ({len(lines)} lines)")

if __name__ == "__main__":
    main()